### ISSUE TITLE
Spec couldn't start with msgpack 0.7.6 and Fluentd v0.14.0.rc.3 (master@a340627)

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluent-logger-ruby#51]
### How to reproduce

Apply the following patch:

``` diff
diff --git a/Gemfile b/Gemfile
index 624a756..805f968 100644
--- a/Gemfile
+++ b/Gemfile
@@ -6,5 +6,5 @@ gemspec
 gem "simplecov", :require => false
 gem "simplecov-vim"

-gem "fluentd"
+gem "fluentd", github: "fluent/fluentd", branch: "master"
 gem 'test-unit'
diff --git a/fluent-logger.gemspec b/fluent-logger.gemspec
index 0192c92..cdf130c 100644
--- a/fluent-logger.gemspec
+++ b/fluent-logger.gemspec
@@ -30,7 +30,7 @@ EOF
   gem.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
   gem.require_paths = ['lib']

-  gem.add_dependency "msgpack", [">= 0.4.4", "!= 0.5.0", "!= 0.5.1", "!= 0.5.2", "!= 0.5.3", "< 0.6.0"]
+  gem.add_dependency "msgpack", ['>= 0.7.6', '< 0.8']
   gem.add_development_dependency 'rake', '>= 0.9.2'
   gem.add_development_dependency 'rspec', '>= 3.0.0'
   gem.add_development_dependency 'rspec-its', '>= 1.1.0'
```

Got the following result:

``` log
$ bundle exec rake spec
/Users/hhatake/.rbenv/versions/2.3.0/bin/ruby -I/Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib:/Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-support-3.4.1/lib /Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec spec/console_logger_spec.rb spec/fluent_logger_spec.rb spec/logger_base_spec.rb spec/logger_spec.rb spec/null_logger_spec.rb spec/test_logger_spec.rb
/Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/fluentd-a34062768f6c/lib/fluent/log.rb:58:in `public_instance_method': undefined method `level=' for class `StringIO' (NameError)
    from /Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/fluentd-a34062768f6c/lib/fluent/log.rb:58:in `initialize'
    from /Users/hhatake/Github/fluent-logger-ruby/spec/fluent_logger_spec.rb:13:in `new'
    from /Users/hhatake/Github/fluent-logger-ruby/spec/fluent_logger_spec.rb:13:in `<top (required)>'
    from /Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
    from /Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
    from /Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
    from /Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
    from /Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
    from /Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
    from /Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
    from /Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
    from /Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<main>'
/Users/hhatake/.rbenv/versions/2.3.0/bin/ruby -I/Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib:/Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-support-3.4.1/lib /Users/hhatake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec spec/console_logger_spec.rb spec/fluent_logger_spec.rb spec/logger_base_spec.rb spec/logger_spec.rb spec/null_logger_spec.rb spec/test_logger_spec.rb failed
```

**Comment by cosmo0920** [comment]
This issue is already fixed at master. Closing.
