### ISSUE TITLE
With nanosecond precision the NoMethodError exception handler fails

### ISSUE THREAD

**Issue by andyprinceuk** [fluent/fluent-logger-ruby#77]
For an event with nanosecond precision enabled, and therefore an EventTime object as the time, if an unserialisable object is passed in the msg, it will cause an error in the JSON serialiser and therefore msgpack fails, specifically in this piece of the code: https://github.com/fluent/fluent-logger-ruby/blob/7de55ab45dd87bcb781ff6c62a3e68260bbd9560/lib/fluent/logger/fluent_logger.rb#L191-L195

Example:
```
require 'fluent-logger'
require 'json'
require 'msgpack'

log = Fluent::Logger::FluentLogger.new(nil, :host => 'localhost', :port => 24224)
# Errno has no to_msgpack, but the post will succeed
log.post("myapp.access2", {"error"=> Errno::ETIMEDOUT})
# => true

log_nano = Fluent::Logger::FluentLogger.new(nil, :host => 'localhost', :port => 24224, :nanosecond_precision=>true)
# This time it will generate an obscure error, with the only difference being to enable nanosecond_precision
log_nano.post("myapp.access2", {"error"=> Errno::ETIMEDOUT})
# E, [2019-05-23T10:24:55.096995 #9135] ERROR -- : FluentLogger: Can't convert to msgpack:  ["myapp.access2", #<Fluent::Logger::EventTime:0x00000002152140 @sec=1558607095, @nsec=96875298>, {"error"=>Errno::ETIMEDOUT}]: wrong argument type Fixnum (expected String)
# => false


# The issue stems from this code snippet within the library
factory = MessagePack::Factory.new
factory.register_type(Fluent::Logger::EventTime::TYPE, Fluent::Logger::EventTime)
packer = factory.packer

# Event without EventTime
msg = ['tag', 123456, {"error"=> Errno::ETIMEDOUT}]
packer.pack(msg)
# NoMethodError: undefined method `to_msgpack' for Errno::ETIMEDOUT:Class
#	from (irb):14:in `write'
#	from (irb):14
#	from /usr/bin/irb:11:in `<main>'

# this triggers the rescue, and works to msgpack the message
JSON.parse(JSON.generate(msg)).to_msgpack
# => "\x93\xA3tag\xCE\x00\x01\xE2@\x81\xA5error\xB0Errno::ETIMEDOUT"

# However, with an EventTime
msg_nano = ['tag', Fluent::Logger::EventTime.new(1000, 11000), {"error"=> Errno::ETIMEDOUT}]
packer.pack(msg_nano)
# NoMethodError: undefined method `to_msgpack' for Errno::ETIMEDOUT:Class
#	from (irb):14:in `write'
#	from (irb):14
#	from /usr/bin/irb:11:in `<main>'

# will again trigger the rescue, but this time fails
JSON.parse(JSON.generate(msg_nano)).to_msgpack
# TypeError: wrong argument type Fixnum (expected String)
# 	from /usr/lib/ruby/gems/2.2.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
# 	from /usr/lib/ruby/gems/2.2.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
# 	from (irb):22
# 	from /usr/bin/irb:11:in `<main>'

# It is specifically the JSON.generate that throws
JSON.generate(msg_nano)
# TypeError: wrong argument type Fixnum (expected String)
# 	from /usr/lib/ruby/gems/2.2.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
# 	from /usr/lib/ruby/gems/2.2.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
# 	from (irb):23
# 	from /usr/bin/irb:11:in `<main>'
```

The rescue clause needs to be able to handle events with an EventTime time

**Comment by andyprinceuk** [comment]
I think the fix may be as simple as updating:
https://github.com/fluent/fluent-logger-ruby/blob/7de55ab45dd87bcb781ff6c62a3e68260bbd9560/lib/fluent/logger/fluent_logger.rb#L46-L48
to return
`@sec.to_json` instead of `@sec`

**Comment by zuk** [comment]
> I think the fix may be as simple as updating:
> 
> https://github.com/fluent/fluent-logger-ruby/blob/7de55ab45dd87bcb781ff6c62a3e68260bbd9560/lib/fluent/logger/fluent_logger.rb#L46-L48
> 
> to return
> `@sec.to_json(*args)` instead of `@sec`

This worked for me. Until a fix is released, it's possible to monkey-patch `EventTime#to_json` to get this fix in place, but it's a bit tricky as you need to do it _after_ you call `FluentLogger.open`. This is how I did it:

```
   ::Fluent::Logger::EventTime.send(:define_method, :to_json) do |*args|
        @sec.to_json(*args)
  end
```

**Comment by ganmacs** [comment]
Thank you so much for your report! #81 should fix this issue.
